### ISSUE TITLE
发现三个问题

### ISSUE THREAD

**Issue by XljBear** [xu42/pay#10]
listening.php中
1.5行的获取raw数据在PHP7中已不被支持建议更改为 file_get_contents('php://input');
2.18行使用的$reqMsg并未定义过
3.测试时发现回调信息中TRADE_SUCCESS状态的msg里没有qrid了

截取了一下
{"client_id":"e7a240707be6433210","id":"E20181015153719004300013","kdt_id":41580239,"kdt_name":"xxxx","mode":1,"msg":"%7B%22update_time%22:%222018-10-15%2015:37:20%22,%22tid%22:%22E20181015153719004300013%22%7D","msg_id":"f15a216e-8438-40ca-be7f-cbbe33f4b4c8","sendCount":0,"sign":"3c3d3265d4ebdb6c745f9a7cabb249d2","status":"TRADE_SUCCESS","test":false,"type":"trade_TradeSuccess","version":1539589064}

**Comment by XljBear** [comment]
然后发现之前注册的是微商城，删除后重新按照步骤注册了微小店，手机也装了app完成了个人验证，但是调用接口就拿不到access_token了报错wrong server pay config
clientSecret等信息也确认正确了

**Comment by xu42** [comment]
@XljBear 问题2[已修复](https://github.com/xu42/pay/blob/master/public/listening.php#L17)，问题3需要监听“PAID”事件。

**Comment by XljBear** [comment]
@xu42 那是不是付款成功应该使用PAID事件而不用TRADE_SUCCESS

**Comment by xu42** [comment]
@XljBear 是的，可以看这里的 [升级引导](https://blog.xu42.cn/2017/11/26/person-website-instant-payment-solution/#%E5%8D%87%E7%BA%A7)

**Comment by XljBear** [comment]
@xu42 好哒非常感谢~希望有赞平台能持久~对于个人开发者很不错了
