### ISSUE TITLE
php start.php, while it doesn't work!

### ISSUE THREAD

**Issue by andyliu24** [xu42/pay#3]
`PHP Fatal error:  require_once(): Failed opening required '/data/wwwroot/pay/src/../vendor/autoload.php' (include_path='.:/usr/local/php/lib/php') in /data/wwwroot/pay/src/start.php on line 3
`

where's the vendor/autoload.php? 
i can't find it in its parent directory.
  
by the way, i can't browse the tutorial on your blog.
`blog.xu42.cn redirected you too many times.
`
![image](https://user-images.githubusercontent.com/24978668/34637921-5a48bc00-f2fb-11e7-98c6-769ba935b3d8.png)

**Comment by xu42** [comment]
1. You should first execute `composer update` in `/data/wwwroot/pay` directory.
2. It's a bug about CDN config, It has been fixed, Thanks

**Comment by andyliu24** [comment]
@xu42 
Thanks a lot.
