### ISSUE TITLE
有赞平台每年的使用费也不低

### ISSUE THREAD

**Issue by Joey-Lee** [xu42/pay#6]
昨天刚注册，今天有赞的客服就打电话给我了。只能免费使用7天，之后继续使用必须交费。

**Comment by Joey-Lee** [comment]
哦，我试试，谢谢啦！

**Comment by yingziaxiba** [comment]
PUSH FAILED CODE: 405 RETURN:
405 Not Allowed              大佬，，接收不到支付状态，405 错误，回调地址    pay.iwadong.com  我换成ip也不行

**Comment by Joey-Lee** [comment]
close.
